# Generated by Django 5.2.6 on 2026-09-02 08:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('READ', 'Read'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE_ATTEMPT', 'Delete attempt')], max_length=20)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('request_path', models.CharField(max_length=500)),
                ('request_id', models.UUIDField(default=uuid.uuid4)),
                ('metadata', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
