# Generated by Django 5.2.6 on 2026-09-02 08:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_confirmed', models.BooleanField()),
                ('drug_confirmed', models.BooleanField()),
                ('dose_confirmed', models.BooleanField()),
                ('route_confirmed', models.BooleanField()),
                ('time_confirmed', models.BooleanField()),
                ('documentation', models.TextField()),
                ('reason', models.TextField()),
                ('response', models.TextField()),
                ('outcome', models.CharField(choices=[('ADMINISTERED', 'Administered'), ('WITHHELD', 'Withheld'), ('REFUSED', 'Refused'), ('MISSED', 'Missed')], max_length=20)),
                ('administered_at', models.DateTimeField()),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrations', to='medications.medicationorder')),
            ],
        ),
    ]
