# Generated by Django 5.2.6 on 2026-09-02 08:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drug', models.CharField(max_length=200)),
                ('dose', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=100)),
                ('scheduled_time', models.TimeField()),
                ('documentation_instructions', models.TextField()),
                ('reason', models.TextField()),
                ('expected_response', models.TextField()),
                ('prn', models.BooleanField(default=False)),
                ('prn_protocol', models.TextField(blank=True)),
                ('prescriber', models.CharField(max_length=200)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CEASED', 'Ceased')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medication_orders', to='clients.client')),
            ],
        ),
    ]
