# Generated by Django 5.2.6 on 2026-09-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('RN', 'Registered nurse'), ('CARER', 'Support worker / carer'), ('COORDINATOR', 'Coordinator'), ('MANAGEMENT', 'Group home management'), ('GP', 'General practitioner'), ('PHARMACIST', 'Pharmacist'), ('ADMIN', 'Administrator')], default='CARER', max_length=20),
        ),
    ]
